package fi.anssi.kalakartta.ui

import org.junit.Assert.assertEquals
import org.junit.Test

class SettingsPreferencesTest {

    @Test
    fun heatmapAndRouteDefaultsRemainCompatible() {
        assertEquals(false, SettingsDefaults.SHOW_SCALE_BAR)
        assertEquals(false, SettingsDefaults.SHOW_MEASUREMENT_TOOL)
        assertEquals(true, SettingsDefaults.AUTO_CENTER_ON_START)
        assertEquals("OSM", SettingsDefaults.MAP_SOURCE)
        assertEquals("", SettingsDefaults.MML_API_KEY)
        assertEquals(false, SettingsDefaults.SHOW_QUICK_MAP_SOURCE)
        assertEquals(true, SettingsDefaults.SHOW_LIVE_SESSION_ROUTE)
        assertEquals(10, SettingsDefaults.LOCATION_CHECK_INTERVAL)
        assertEquals(30, SettingsDefaults.MIN_TRACK_POINT_INTERVAL)
        assertEquals(300, SettingsDefaults.MAX_TRACK_POINT_INTERVAL)
        assertEquals(20, SettingsDefaults.MIN_TRACK_POINT_DISTANCE)
        assertEquals("", SettingsDefaults.DEFAULT_FISHERMAN)
        assertEquals(false, SettingsDefaults.SHOW_FISHERMAN_ON_MAP)
        assertEquals(1.0f, SettingsDefaults.FISH_ICON_SCALE)
        assertEquals(1.0f, SettingsDefaults.OTHER_ICON_SCALE)
        assertEquals(true, SettingsDefaults.WEATHER_ENABLED)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_ENABLED)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_ONLY_FISHING)
        assertEquals(30, SettingsDefaults.TALKING_CLOCK_INTERVAL)
        assertEquals("", SettingsDefaults.TALKING_CLOCK_SALUTATION)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_BATTERY)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_WEATHER)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_SUNSET)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_SUNRISE)
        assertEquals(2, SettingsDefaults.TALKING_CLOCK_SUNSET_LIMIT)
        assertEquals(2, SettingsDefaults.TALKING_CLOCK_SUNRISE_LIMIT)
        assertEquals(false, SettingsDefaults.TALKING_CLOCK_WEATHER_OPTION_ENABLED)
        assertEquals(3, SettingsDefaults.TALKING_CLOCK_WEATHER_DEFAULT_HOURS)
        assertEquals(false, SettingsDefaults.HEATMAP_ENABLED)
        assertEquals(false, SettingsDefaults.FISHING_ROUTES_ENABLED)
        assertEquals(false, SettingsDefaults.HEATMAP_FILTER_ENABLED)
        assertEquals(false, SettingsDefaults.ROUTES_FILTER_ENABLED)
        assertEquals(false, SettingsDefaults.SHOW_HEATMAP_SHORTCUT)
        assertEquals(0, SettingsDefaults.HEATMAP_SHORTCUT_MODE)
        assertEquals(1, SettingsDefaults.HEATMAP_MIN_POINTS)
        assertEquals(50, SettingsDefaults.HEATMAP_MAX_POINTS)
        assertEquals(1, SettingsDefaults.HEATMAP_MIN_POINTS_BY_POINTS)
        assertEquals(50, SettingsDefaults.HEATMAP_MAX_POINTS_BY_POINTS)
        assertEquals(1, SettingsDefaults.HEATMAP_MIN_POINTS_BY_SESSIONS)
        assertEquals(5, SettingsDefaults.HEATMAP_MAX_POINTS_BY_SESSIONS)
        assertEquals(true, SettingsDefaults.HEATMAP_AUTO_CONFIGURE)
        assertEquals(false, SettingsDefaults.HEATMAP_REMOVE_TRANSITIONS)
        assertEquals(0, SettingsDefaults.HEATMAP_REMOVE_TRANSITIONS_MODE)
        assertEquals(300.0f, SettingsDefaults.HEATMAP_GRID_SIZE)
        assertEquals(10.0f, SettingsDefaults.HEATMAP_MAX_SPEED)
        assertEquals(50_000, SettingsDefaults.MAX_TRACK_POINTS)
        assertEquals(10_000, SettingsDefaults.MAX_HEATMAP_CELLS)
        assertEquals(10.0f, SettingsDefaults.HEATMAP_MIN_ZOOM)
        assertEquals(64.7f, SettingsDefaults.HEATMAP_REFERENCE_LATITUDE)
        assertEquals(true, SettingsDefaults.ROUTES_FADE_ENABLED)
        assertEquals(365, SettingsDefaults.ROUTES_FADE_START_DAYS)
        assertEquals(30, SettingsDefaults.ROUTES_FADE_FULL_DAYS)
    }

    @Test
    fun preferenceKeysRemainCompatible() {
        assertEquals("show_scale_bar", SettingsKeys.SHOW_SCALE_BAR)
        assertEquals("show_measurement_tool", SettingsKeys.SHOW_MEASUREMENT_TOOL)
        assertEquals("auto_center_on_start", SettingsKeys.AUTO_CENTER_ON_START)
        assertEquals("map_source", SettingsKeys.MAP_SOURCE)
        assertEquals("mml_api_key", SettingsKeys.MML_API_KEY)
        assertEquals("show_quick_map_source", SettingsKeys.SHOW_QUICK_MAP_SOURCE)
        assertEquals("quick_select_MML_MAASTO", SettingsKeys.quickSelect("MML_MAASTO"))
        assertEquals("show_live_session_route", SettingsKeys.SHOW_LIVE_SESSION_ROUTE)
        assertEquals("location_check_interval", SettingsKeys.LOCATION_CHECK_INTERVAL)
        assertEquals("min_track_point_interval", SettingsKeys.MIN_TRACK_POINT_INTERVAL)
        assertEquals("max_track_point_interval", SettingsKeys.MAX_TRACK_POINT_INTERVAL)
        assertEquals("min_track_point_distance", SettingsKeys.MIN_TRACK_POINT_DISTANCE)
        assertEquals("default_fisherman", SettingsKeys.DEFAULT_FISHERMAN)
        assertEquals("show_fisherman_on_map", SettingsKeys.SHOW_FISHERMAN_ON_MAP)
        assertEquals("fish_icon_scale", SettingsKeys.FISH_ICON_SCALE)
        assertEquals("other_icon_scale", SettingsKeys.OTHER_ICON_SCALE)
        assertEquals("weather_enabled", SettingsKeys.WEATHER_ENABLED)
        assertEquals("talking_clock_enabled", SettingsKeys.TALKING_CLOCK_ENABLED)
        assertEquals("talking_clock_only_fishing", SettingsKeys.TALKING_CLOCK_ONLY_FISHING)
        assertEquals("talking_clock_interval", SettingsKeys.TALKING_CLOCK_INTERVAL)
        assertEquals("talking_clock_salutation", SettingsKeys.TALKING_CLOCK_SALUTATION)
        assertEquals("talking_clock_battery", SettingsKeys.TALKING_CLOCK_BATTERY)
        assertEquals("talking_clock_weather", SettingsKeys.TALKING_CLOCK_WEATHER)
        assertEquals("talking_clock_sunset", SettingsKeys.TALKING_CLOCK_SUNSET)
        assertEquals("talking_clock_sunrise", SettingsKeys.TALKING_CLOCK_SUNRISE)
        assertEquals("talking_clock_sunset_limit", SettingsKeys.TALKING_CLOCK_SUNSET_LIMIT)
        assertEquals("talking_clock_sunrise_limit", SettingsKeys.TALKING_CLOCK_SUNRISE_LIMIT)
        assertEquals("talking_clock_weather_3h", SettingsKeys.talkingClockWeather(3))
        assertEquals("heatmap_enabled", SettingsKeys.HEATMAP_ENABLED)
        assertEquals("fishing_routes_enabled", SettingsKeys.FISHING_ROUTES_ENABLED)
        assertEquals("heatmap_filter_enabled", SettingsKeys.HEATMAP_FILTER_ENABLED)
        assertEquals("routes_filter_enabled", SettingsKeys.ROUTES_FILTER_ENABLED)
        assertEquals("show_heatmap_shortcut", SettingsKeys.SHOW_HEATMAP_SHORTCUT)
        assertEquals("heatmap_shortcut_mode", SettingsKeys.HEATMAP_SHORTCUT_MODE)
        assertEquals("heatmap_color", SettingsKeys.HEATMAP_COLOR)
        assertEquals("heatmap_calculation_method", SettingsKeys.HEATMAP_CALCULATION_METHOD)
        assertEquals("heatmap_min_points", SettingsKeys.HEATMAP_MIN_POINTS)
        assertEquals("heatmap_max_points", SettingsKeys.HEATMAP_MAX_POINTS)
        assertEquals("heatmap_min_points_by_points", SettingsKeys.HEATMAP_MIN_POINTS_BY_POINTS)
        assertEquals("heatmap_max_points_by_points", SettingsKeys.HEATMAP_MAX_POINTS_BY_POINTS)
        assertEquals("heatmap_min_points_by_sessions", SettingsKeys.HEATMAP_MIN_POINTS_BY_SESSIONS)
        assertEquals("heatmap_max_points_by_sessions", SettingsKeys.HEATMAP_MAX_POINTS_BY_SESSIONS)
        assertEquals("heatmap_auto_configure", SettingsKeys.HEATMAP_AUTO_CONFIGURE)
        assertEquals("heatmap_remove_transitions", SettingsKeys.HEATMAP_REMOVE_TRANSITIONS)
        assertEquals("heatmap_remove_transitions_mode", SettingsKeys.HEATMAP_REMOVE_TRANSITIONS_MODE)
        assertEquals("heatmap_grid_size", SettingsKeys.HEATMAP_GRID_SIZE)
        assertEquals("heatmap_max_speed", SettingsKeys.HEATMAP_MAX_SPEED)
        assertEquals("max_track_points", SettingsKeys.MAX_TRACK_POINTS)
        assertEquals("max_heatmap_cells", SettingsKeys.MAX_HEATMAP_CELLS)
        assertEquals("heatmap_min_zoom", SettingsKeys.HEATMAP_MIN_ZOOM)
        assertEquals("heatmap_reference_latitude", SettingsKeys.HEATMAP_REFERENCE_LATITUDE)
        assertEquals("routes_fade_enabled", SettingsKeys.ROUTES_FADE_ENABLED)
        assertEquals("routes_fade_start_days", SettingsKeys.ROUTES_FADE_START_DAYS)
        assertEquals("routes_fade_full_days", SettingsKeys.ROUTES_FADE_FULL_DAYS)
    }
}
